// <auto-generated />
using ChecksumAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace ChecksumAPI.Migrations
{
    [DbContext(typeof(CADbContext))]
    [Migration("13960810091330_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ChecksumAPI.FileChecksum", b =>
                {
                    b.Property<string>("FileUrl");

                    b.Property<byte>("OffsetPercent");

                    b.Property<string>("Algorithm")
                        .IsRequired();

                    b.Property<string>("Checksum")
                        .IsRequired();

                    b.HasKey("FileUrl", "OffsetPercent");

                    b.ToTable("FileChecksums");
                });
#pragma warning restore 612, 618
        }
    }
}
